name: Deploy DocC

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .gitignore

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-26
    env:
      DEVELOPER_DIR: "/Applications/Xcode_26.2.0.app/Contents/Developer"

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check Env
        run: |
          xcodebuild -version
          xcodebuild -list
          xcrun xctrace list devices 2>&1 | grep -v Apple

      - name: Build DocC
        run: |
          xcodebuild docbuild \
            -scheme swift-calculator \
            -destination "generic/platform=iOS" \
            -derivedDataPath DerivedData | \
            xcbeautify && exit ${PIPESTATUS[0]}

          $(xcrun --find docc) process-archive \
             transform-for-static-hosting DerivedData/Build/Products/Debug-*/CalculatorUI.doccarchive \
             --output-path ./docs \
             --hosting-base-path "swift-calculator"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs

  deploy:
    runs-on: ubuntu-slim
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: "https://cybozu.github.io/swift-calculator/documentation/calculatorui/"

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
